// <auto-generated />
using System;
using LMS_Learn_Project.DATA1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS_Learn_Project.Migrations
{
    [DbContext(typeof(STUDENTDATABASEFILE))]
    [Migration("20250212101643_f1")]
    partial class f1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS_Learn_Project.Models.Student", b =>
                {
                    b.Property<Guid>("STUDENT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("STUDENT_age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STUDENT_branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STUDENT_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STUDENT_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STUDENT_phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("STUDENT_ID");

                    b.ToTable("Studentregistertbl");
                });
#pragma warning restore 612, 618
        }
    }
}
